# Generated by Django 3.2.25 on 2025-08-02 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.batch'),
            preserve_default=False,
        ),
    ]
