# Generated by Django 3.2.25 on 2025-08-03 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250802_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='La ubicación solo puede contener letras, números, espacios, guiones y guiones bajos.', regex='^[a-zA-Z0-9\\s_-]+$')]),
        ),
    ]
