# Generated by Django 3.2.25 on 2025-08-03 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_warehouse_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryitem',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_items', to='core.entry'),
        ),
    ]
