# Generated by Django 3.2.25 on 2025-08-10 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_entryitem_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='selling_channel',
        ),
        migrations.AddField(
            model_name='sale',
            name='selling_channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.sellingchannel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outputitem',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_items', to='core.output'),
        ),
    ]
