# Generated by Django 3.2.25 on 2025-08-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250810_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(related_name='suppliers', to='core.Supplier'),
        ),
    ]
