# Generated by Django 3.2.25 on 2025-08-13 00:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250811_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('qr', 'QR')], default='cash', max_length=20)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Venta')], default='purchase', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('full_payment', 'Pago al contado'), ('partial_payment', 'Pago a crédito')], default='full_payment', max_length=25)),
                ('purchase_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El número de factura solo puede contener números.', regex='^\\d+$')])),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.purchase')),
            ],
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='entry',
            name='warehouse_keeper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='output',
            name='warehouse_keeper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('full_payment', 'Pago al contado'), ('partial_payment', 'Pago a crédito')], default='full_payment', max_length=25),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='output',
            name='output_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.AddField(
            model_name='entry',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.purchase'),
        ),
    ]
