# Generated by Django 3.2.25 on 2025-08-13 02:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250812_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, números, espacios, guiones y guiones bajos.', regex='^[a-zA-Z0-9\\s_-]+$')])),
                ('location', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='La ubicación solo puede contener letras, números, espacios, guiones y guiones bajos.', regex='^[a-zA-Z0-9\\s_-]+$')])),
                ('city', models.CharField(choices=[('LP', 'La Paz'), ('CBBA', 'Cochabamba'), ('SCZ', 'Santa Cruz'), ('TJA', 'Tarija'), ('OR', 'Oruro'), ('PT', 'Potosí'), ('CH', 'Chuquisaca'), ('BE', 'Beni'), ('PD', 'Pando')], default='PT', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='core.agency'),
            preserve_default=False,
        ),
    ]
