# Generated by Django 3.2.25 on 2025-08-13 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250812_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellingchannel',
            name='discount',
        ),
    ]
