# Generated by Django 3.2.25 on 2025-08-14 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_sellingchannel_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='supplier',
            name='product',
            field=models.ManyToManyField(related_name='supplier_products', to='core.Product'),
        ),
        migrations.CreateModel(
            name='ProductChannelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('selling_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sellingchannel')),
            ],
        ),
        migrations.AddField(
            model_name='sellingchannel',
            name='product',
            field=models.ManyToManyField(related_name='products', through='core.ProductChannelPrice', to='core.Product'),
        ),
    ]
