# Generated by Django 3.2.25 on 2025-08-16 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20250813_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='core.purchase'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='core.sale'),
        ),
        migrations.AlterField(
            model_name='sellingchannel',
            name='product',
            field=models.ManyToManyField(related_name='selling_channels', through='core.ProductChannelPrice', to='core.Product'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='product',
            field=models.ManyToManyField(related_name='suppliers', to='core.Product'),
        ),
    ]
