# Generated by Django 3.2.25 on 2025-08-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20250815_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('distribution', 'Distribución'), ('showroom', 'Showroom'), ('projects', 'Proyectos')], default='showroom', max_length=20),
        ),
    ]
