# Generated by Django 3.2.25 on 2025-08-19 00:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_client_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='nit',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El CI/NIT debe tener 7-11 dígitos seguidos opcionalmente de un guión y 2 letras mayúsculas (e.g., 1234567-AB o 12345678).', regex='^\\d{7,11}(-[A-Z]{2})?$')]),
        ),
    ]
