# Generated by Django 3.2.25 on 2025-08-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20250818_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('realizado', 'Realizada'), ('terminado', 'Terminada')], default='realizado', max_length=20),
        ),
        migrations.AlterField(
            model_name='agency',
            name='city',
            field=models.CharField(choices=[('La Paz', 'LP'), ('Cochabamba', 'CBBA'), ('Santa Cruz', 'SCZ'), ('Tarija', 'TJA'), ('Oruro', 'OR'), ('Potosi', 'PT'), ('Chuquisaca', 'CH'), ('Beni', 'BE'), ('Pando', 'PD')], default='Potosi', max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('distribucion', 'Distribución'), ('showroom', 'Showroom'), ('proyecto', 'Proyectos')], default='showroom', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('qr', 'QR')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], default='compra', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('contado', 'Pago al contado'), ('credito', 'Pago a crédito')], default='contado', max_length=25),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('contado', 'Pago al contado'), ('credito', 'Pago a crédito')], default='contado', max_length=25),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('generado', 'Generada'), ('realizado', 'Realizada'), ('terminado', 'Terminada'), ('rechazado', 'Rechazada')], default='generado', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('transaction_id', 'transaction_type'), name='unique_transaction'),
        ),
    ]
