# Generated by Django 3.2.25 on 2025-08-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20250823_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_of_measurement',
        ),
    ]
