# Generated by Django 3.2.25 on 2025-08-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_product_unit_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(default='UN', max_length=10),
            preserve_default=False,
        ),
    ]
