# Generated by Django 3.2.25 on 2025-09-07 04:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20250901_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sale'),
        ),
        migrations.AlterField(
            model_name='productchannelprice',
            name='selling_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_channel_price', to='core.sellingchannel'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El número de factura solo puede contener números.', regex='^\\d+$')]),
        ),
    ]
