# Generated by Django 3.2.25 on 2025-09-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20250908_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('proforma', 'Proforma'), ('realizado', 'Realizada'), ('terminado', 'Terminada'), ('rechazado', 'Rechazada')], default='generado', max_length=20),
        ),
    ]
