# Generated by Django 3.2.25 on 2025-09-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_done_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_perform_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
