# Generated by Django 3.2.25 on 2025-09-09 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20250908_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.agency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.agency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.agency'),
            preserve_default=False,
        ),
    ]
