# Generated by Django 3.2.25 on 2025-09-10 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20250909_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.agency'),
        ),
    ]
