# Generated by Django 3.2.25 on 2025-09-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_user_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sub_total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
