# Generated by Django 3.2.25 on 2025-09-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20250912_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('proforma', 'Proforma'), ('contado', 'Pago al contado'), ('credito', 'Pago a crédito')], default='contado', max_length=25),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('proforma', 'Proforma'), ('realizado', 'Realizada'), ('terminado', 'Terminada'), ('rechazado', 'Rechazada')], default='proforma', max_length=20),
        ),
    ]
