# Generated by Django 3.2.25 on 2025-09-26 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_entryitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='entryitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='outputitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='maximum_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reserved_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('reserved_stock', models.PositiveIntegerField(default=0)),
                ('available_stock', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=0)),
                ('maximum_stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='core.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse')),
            ],
            options={
                'unique_together': {('product', 'warehouse')},
            },
        ),
        migrations.AddField(
            model_name='entryitem',
            name='product_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.productstock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outputitem',
            name='product_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.productstock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.productstock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.productstock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='product_stock',
            field=models.ManyToManyField(related_name='warehouses', through='core.ProductStock', to='core.Product'),
        ),
    ]
