# Generated by Django 3.2.25 on 2025-09-27 03:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20250926_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='output',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, números y espacios.', regex='^[a-zA-Z0-9\\sñÑáéíóúÁÉÍÓÚ]+$')]),
        ),
    ]
