# Generated by Django 3.2.25 on 2025-09-29 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20250926_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_stocks', to='core.warehouse'),
        ),
    ]
