# Generated by Django 3.2.25 on 2025-10-02 02:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_productstock_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='entered_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='dispatched_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.purchase'),
        ),
        migrations.AlterField(
            model_name='entryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='outputitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, números y espacios.', regex='^[a-zA-Z0-9\\sñÑáéíóúÁÉÍÓÚ]+$')]),
        ),
    ]
