# Generated by Django 3.2.25 on 2025-10-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20251001_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='output',
            name='sale',
        ),
        migrations.AddField(
            model_name='entryitem',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.purchaseitem'),
        ),
        migrations.AddField(
            model_name='outputitem',
            name='sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.saleitem'),
        ),
    ]
