# Generated by Django 3.2.25 on 2025-10-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20251002_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='deliver_status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcialmente Ingresado'), ('completado', 'Completado')], default='pendiente', max_length=15),
        ),
    ]
