# Generated by Django 3.2.25 on 2025-10-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_purchase_deliver_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='deliver_status',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcialmente Ingresado'), ('completado', 'Completado')], default='pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcialmente Entregado'), ('completado', 'Completado')], default='pendiente', max_length=15),
        ),
    ]
