# Generated by Django 3.2.25 on 2025-10-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_entryitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='output',
            name='warehouse',
        ),
    ]
