# Generated by Django 3.2.25 on 2025-10-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20251005_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='damaged_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
