# Generated by Django 3.2.25 on 2025-10-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_productstock_damaged_stock'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_transaction',
        ),
    ]
