# Generated by Django 3.2.25 on 2025-10-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_payment_unique_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
