# Generated by Django 3.2.25 on 2025-10-15 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_sale_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.purchase'),
        ),
        migrations.AddField(
            model_name='output',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sale'),
        ),
    ]
