# Generated by Django 3.2.25 on 2025-10-16 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20251014_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='core.sale'),
        ),
    ]
