# Generated by Django 3.2.25 on 2025-10-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_output_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='invoice_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
