# Generated by Django 3.2.25 on 2025-10-17 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_output_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.agency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='output',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.agency'),
            preserve_default=False,
        ),
    ]
