# Generated by Django 3.2.25 on 2025-12-19 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20251016_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_reports', 'Puede ver reportes')]},
        ),
    ]
