# Generated by Django 3.2.25 on 2026-01-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pre_invoice_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
