# Generated by Django 3.2.25 on 2026-01-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_sale_pre_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='pre_invoice_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
