# Generated by Django 3.2.25 on 2026-01-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_sale_pre_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
