# Generated by Django 3.2.25 on 2026-01-08 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_output_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El número de factura solo puede contener números.', regex='^\\d+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('supplier', 'invoice_number')},
        ),
    ]
