# Generated by Django 3.2.25 on 2026-06-20 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20260108_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='nit',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El CI/NIT debe tener 7-11 dígitos, opcionalmente seguidos de un guión y 2 letras mayúsculas (e.g., 1234567-AB).', regex='^\\d{7,11}(-[A-Z]{2})?$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nit',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El NIT debe tener 7-11 dígitos, opcionalmente seguidos de un guión y 2 letras mayúsculas (e.g., 1234567-AB o 12345678).', regex='^\\d{7,11}(-[A-Z]{2})?$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='ci',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El CI/NIT debe tener 7-11 dígitos, opcionalmente seguidos de un guión y 2 letras mayúsculas (e.g., 1234567-AB).', regex='^\\d{7,11}(-[A-Z]{2})?$')]),
        ),
    ]
