# Generated by Django 3.2.25 on 2026-06-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_product_unit_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.measureunit'),
        ),
    ]
