# Generated by Django 3.2.25 on 2026-06-20 19:03

from django.db import migrations, models
import django.db.models.deletion


def create_default_measure_unit(apps, schema_editor):
    MeasureUnit = apps.get_model('core', 'MeasureUnit')
    Product = apps.get_model('core', 'Product')

    default_unit, _ = MeasureUnit.objects.get_or_create(
        name='Unidad',
    )
    Product.objects.filter(measure_unit__isnull=True).update(
        measure_unit=default_unit,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_product_measure_unit'),
    ]

    operations = [
        migrations.RunPython(
            create_default_measure_unit,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.measureunit',
            ),
        ),
    ]
