# Generated by Django 3.2.25 on 2026-06-20 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_product_measure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.measureunit'),
            preserve_default=False,
        ),
    ]
