# Generated by Django 3.2.25 on 2026-06-20 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_product_measure_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='line',
            field=models.CharField(default='test', max_length=50, validators=[django.core.validators.RegexValidator(message='La línea solo puede contener letras, números, espacios, guiones y guiones bajos.', regex='^[a-zA-Z0-9\\s_-]+$')]),
            preserve_default=False,
        ),
    ]
