# Generated by Django 3.2.25 on 2026-06-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_product_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('anticipo', 'Anticipo'), ('venta', 'Venta')], default='anticipo', max_length=20),
        ),
    ]
