# Generated by Django 3.2.25 on 2026-06-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
