# Generated by Django 3.2.25 on 2026-06-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_sale_credit_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('anticipo', 'Anticipo'), ('venta', 'Venta')], default='venta', max_length=20),
        ),
    ]
