# Generated by Django 3.2.25 on 2026-07-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_remove_saleitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryitem',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='outputitem',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='available_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='damaged_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='maximum_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='minimum_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='reserved_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='entered_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='dispatched_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
