# Generated by Django 3.2.25 on 2026-07-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20260702_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
