# Generated by Django 3.2.25 on 2026-07-03 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_sale_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El CI/NIT debe tener 7-11 dígitos, opcionalmente seguidos de un guión y 2 letras mayúsculas (e.g., 1234567-AB).', regex='^\\d{7,11}(-[A-Z]{2})?$')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('proforma', 'Proforma'), ('anticipo', 'Anticipo'), ('contado', 'Pago al contado'), ('credito', 'Pago a crédito')], default='contado', max_length=25),
        ),
    ]
