# Generated by Django 3.2.25 on 2026-07-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20260703_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_anticipation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('proforma', 'Proforma'), ('contado', 'Pago al contado'), ('credito', 'Pago a crédito')], default='contado', max_length=25),
        ),
    ]
