# Generated by Django 3.2.25 on 2026-07-15 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20260703_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, números, espacios, guiones y guiones bajos.', regex='^[a-zA-Z0-9\\s_-]+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('category', 'name')},
        ),
    ]
