# Generated by Django 3.2.25 on 2026-07-15 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20260714_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, números, espacios, guiones y guiones bajos.', regex='^[a-zA-Z0-9\\s_-]+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('agency', 'name')},
        ),
    ]
