# Generated by Django 3.2.25 on 2026-07-16 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_remove_product_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, números, espacios, guiones y guiones bajos.', regex='^[a-zA-Z0-9 .,_-]+$')]),
        ),
    ]
