# Generated by Django 3.2.25 on 2026-07-16 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, números, espacios, guiones, guiones bajos, puntos, comas y acentos.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ0-9 .,_-]+$')]),
        ),
    ]
