# Generated by Django 3.2.25 on 2026-07-16 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El código solo puede contener letras, números, espacios, guiones y guiones bajos.', regex='^[a-zA-ZñÑ0-9\\s_-]+$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, números, espacios, guiones, guiones bajos, puntos, comas y acentos.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ0-9 .,_-]+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('batch', 'code')},
        ),
    ]
