# Generated by Django 3.2.25 on 2026-07-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20260723_1017'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('batch', 'code', 'name')},
        ),
    ]
