# Generated by Django 3.2.25 on 2026-07-23 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El NIT debe tener 7-11 dígitos, opcionalmente seguidos de un guión y 2 letras mayúsculas (e.g., 1234567-AB o 12345678).', regex='^\\d{7,11}(-[A-Z]{2})?$')]),
        ),
    ]
