# Generated by Django 3.2.25 on 2026-07-28 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20260723_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='El número de factura solo puede contener números.', regex='^\\d+$')]),
        ),
    ]
