# Generated by Django 3.2.25 on 2026-07-29 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_entry_invoice_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='agency',
        ),
    ]
