# Generated by Django 3.2.25 on 2026-07-29 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20260728_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='product_stock',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.product'),
            preserve_default=False,
        ),
    ]
