# Generated by Django 3.2.25 on 2026-08-10 23:45

import uuid

from django.db import migrations, models


def backfill_idempotency_keys(apps, schema_editor):
    Sale = apps.get_model('core', 'Sale')
    for sale in Sale.objects.filter(idempotency_key__isnull=True).iterator():
        sale.idempotency_key = str(uuid.uuid4())
        sale.save(update_fields=['idempotency_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_sale_idempotency_key'),
    ]

    operations = [
        migrations.RunPython(
            backfill_idempotency_keys,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='sale',
            name='idempotency_key',
            field=models.CharField(
                db_index=True,
                default=uuid.uuid4,
                max_length=255,
                unique=True,
            ),
        ),
    ]
