# Generated by Django 3.2.25 on 2026-08-18 16:08

from django.db import migrations, models
import django.db.models.deletion


def _product_category_column_exists(schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        columns = connection.introspection.get_table_description(
            cursor, 'core_product'
        )
    return any(column.name == 'category_id' for column in columns)


def add_product_category_if_missing(apps, schema_editor):
    if _product_category_column_exists(schema_editor):
        return

    Product = apps.get_model('core', 'Product')
    Category = apps.get_model('core', 'Category')
    field = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        null=True,
    )
    field.set_attributes_from_name('category')
    schema_editor.add_field(Product, field)


def copy_category_from_batch_to_product(apps, schema_editor):
    Product = apps.get_model('core', 'Product')
    for product in Product.objects.select_related('batch').iterator():
        if product.batch_id:
            product.category_id = product.batch.category_id
            product.save(update_fields=['category_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_sale_idempotency_key'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='category',
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='core.category',
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_product_category_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
        ),
        migrations.RunPython(
            copy_category_from_batch_to_product,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='core.category',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='batch',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='core.batch',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='batch',
            name='category',
        ),
    ]
