# Generated by Django 3.2.25 on 2026-08-18 22:43

from django.db import migrations, models
import django.db.models.deletion


def copy_batch_from_product_to_productstock(apps, schema_editor):
    ProductStock = apps.get_model('core', 'ProductStock')
    for product_stock in ProductStock.objects.select_related(
            'product').iterator():
        product_stock.batch_id = product_stock.product.batch_id
        product_stock.save(update_fields=['batch_id'])


def merge_duplicate_catalog_products(apps, schema_editor):
    """Merge catalog products that only differed by lote."""
    from django.db.models import Count

    Product = apps.get_model('core', 'Product')
    ProductStock = apps.get_model('core', 'ProductStock')
    PurchaseItem = apps.get_model('core', 'PurchaseItem')
    ProductChannelPrice = apps.get_model('core', 'ProductChannelPrice')

    groups = (
        Product.objects.values('code', 'name')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
    )
    for group in groups:
        products = list(
            Product.objects.filter(
                code=group['code'], name=group['name']
            ).order_by('id')
        )
        keeper = products[0]
        keeper_channel_ids = set(
            ProductChannelPrice.objects.filter(
                product=keeper
            ).values_list('selling_channel_id', flat=True)
        )
        for extra in products[1:]:
            ProductStock.objects.filter(product=extra).update(product=keeper)
            PurchaseItem.objects.filter(product=extra).update(product=keeper)

            extra_prices = ProductChannelPrice.objects.filter(product=extra)
            for price in extra_prices:
                if price.selling_channel_id in keeper_channel_ids:
                    price.delete()
                else:
                    price.product = keeper
                    price.save(update_fields=['product'])
                    keeper_channel_ids.add(price.selling_channel_id)

            for supplier in extra.suppliers.all():
                keeper.suppliers.add(supplier)
            extra.suppliers.clear()
            extra.delete()


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0081_auto_20260818_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='batch',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='product_stocks',
                to='core.batch',
            ),
        ),
        migrations.RunPython(
            copy_batch_from_product_to_productstock,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='productstock',
            name='batch',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='product_stocks',
                to='core.batch',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('product', 'warehouse', 'batch')},
        ),
        migrations.RunPython(
            merge_duplicate_catalog_products,
            migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('code', 'name')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='batch',
        ),
    ]
